### ISSUE TITLE
Problems with macOS 10.14 Mojave - Outline View Rendering

### ISSUE THREAD

**Issue by trainsatsea** [archimatetool/archi#401]
### Version of Archi, Operating System
Archi version 4.3.0 build 201809101333
ruuning on macOs Mojave version 10.14 (18A391) kernel: Darwin 18.0.0

### Expected Behaviour
I expext to see just one representation of the view. which scales with the window or where the window slides over the view

### Actual Behaviour
the view is either trunkcated or shown multiple times

### Steps to Reproduce the Behaviour
1. open a model 
2. select a view
3. open the outline window
4. resize the outline window by dragging the sides up / down or left / right

See the attached screenshots

<img width="568" alt="schermafbeelding 2018-10-01 om 15 59 54" src="https://user-images.githubusercontent.com/18326651/46293320-70e94400-c593-11e8-905c-1cd1fa8a5b55.png">
<img width="493" alt="schermafbeelding 2018-10-01 om 16 00 58" src="https://user-images.githubusercontent.com/18326651/46293322-7181da80-c593-11e8-86a8-446682ec9ded.png">
<img width="679" alt="schermafbeelding 2018-10-01 om 16 01 58" src="https://user-images.githubusercontent.com/18326651/46293323-7181da80-c593-11e8-8633-edc05b5e90e0.png">

**Comment by Phillipus** [comment]
I've not seen this before. Which version of Windows are you using?

Can you test and compare on another machine?

**Comment by trainsatsea** [comment]
I'm running macOs Mojave version 10.14.
I will install archi on a windows 10 VM and see if i can reproduce the behaviour.

**Comment by Phillipus** [comment]
This is probably an issue with macOs Mojave. I can't test on Mojave as my laptop can't run it.

**Comment by Phillipus** [comment]
I suspect that Mojave has a new graphics engine (Metal) that might break some things in the graphics libraries that Archi uses. I'd be interested to know if you see any other graphical issues.

**Comment by trainsatsea** [comment]
i do see some differences

**Comment by Phillipus** [comment]
> backspace behaves different

It should act as "delete".

**Comment by trainsatsea** [comment]
it deletes the whole view when adding one and not the typo i was correcting

**Comment by Phillipus** [comment]
What is it that you editing? Where is the focus? Is it in the rename box on the tree?

**Comment by trainsatsea** [comment]
in the modeltree, right click <add view>, focus is on the name <New Archimate View>, it type the views name, which contains a typo. On backspace then the view is removed instead of the view name being corrected.

**Comment by Phillipus** [comment]
When you are editing a name in the model tree, and focus is in the text cell editor is the red "X" on the toolbar active or greyed out? It should be greyed out.

Here's what should happen:

When a text cell editor in Archi gets the focus it temporarily disables any global key bindings that could affect the edit. This includes the Backspace, Delete, Undo, Redo, Select All and other global key bindings. They should therefore be greyed out.

**Comment by trainsatsea** [comment]
the red X is not grayed out ... see screenshot. This one is taken after new view. 
<img width="825" alt="schermafbeelding 2018-10-01 om 21 32 31" src="https://user-images.githubusercontent.com/18326651/46311165-9ee57d00-c5c1-11e8-9688-be4b3f9a53be.png">

**Comment by Phillipus** [comment]
Thanks for screenshot. If you edit the name of an element in-place in a View diagram is the red X enabled?

![image 1](https://user-images.githubusercontent.com/600504/46311406-fb449e80-c5b9-11e8-8556-3e2d295cfb54.png)

**Comment by trainsatsea** [comment]
in that case it is not enabled,  when I drag a new element into a view. In the previous case, when changing the name of a existing view the red x is not enabled aswell. The X is only enabled when adding a view. If I add another element by adding it to the tree the red X is disabled

**Comment by Phillipus** [comment]
> The X is only enabled when adding a view

If you right-click on an element in the tree and select "Rename" is it enabled or disabled?

This could be the key information I need. The editing sequence depends on certain events being fired at the right time.

**Comment by Phillipus** [comment]
Actually is this behaviour only when you do one of the following actions and the cell editor is activated?:

- New Model
- New Element
- New Folder
- New View

**Comment by trainsatsea** [comment]
when right clicking an element in the tree it is disabled
new folder - > disabled
new view -> enabled
new model -> disabled
new element - > disabled, actualy you see enabled, followed by text entering in the modelname, then disabled.

**Comment by Phillipus** [comment]
Actually I'm seeing it on Windows, too. So that's a separate issue. This issue can focus on the original issue and Mojave specific things.

**Comment by trainsatsea** [comment]
i do have two mac's I can make one available for you if you like?

**Comment by trainsatsea** [comment]
i will send you a mail tomorrow.

**Comment by Phillipus** [comment]
The Backspace key on Mac problem is now fixed. The fix will be in the next release.

It was a side effect of having a different text cell editor introduced in Archi version 4.1 and affects all platforms. Here's the sequence of events in the code:

1. Add a new View to the Tree
2. Open the View
3. Select the new node in the Tree and activate the text cell editor for renaming
4. When activating the text cell editor, disable the global key bindings for the Tree

Because of stage (2) the View steals the focus and therefore stage (4) does not happen. And because the global key bindings are still active, the Backspace key on Mac is still bound to the Delete action in the Tree.

Took a long time to find the problem, but should be fixed now. Thanks for reporting it.

**Comment by xmstspider** [comment]
Hello,

I tested this initial issue with the Outline on MacOS 10.14 Mojave, Windows 10 x64 and Fedora 28 x64. No problem on Fedora and Windows, but on Mojave it is the same as on the screenshots...

**Comment by Phillipus** [comment]
Is it a drawing refresh issue? What happens if you maximise, minimise, etc the Outline tab?

**Comment by Phillipus** [comment]
As I can't test with Mojave we need someone else to take a look at this.

We need to determine if this is a macOs issue or something that needs to change in the Eclipse drawing library (SWT / GEF/ Draw2D). 

There are other Eclipse-based tools that use a thumbnail image in an Outline pane - Eclipse Sirius diagrams and the "Ecore Diagram Editor" for Eclipse are ones that I am aware of.

It would be good if someone with Mojave were able to see how these tools perform.

**Comment by xmstspider** [comment]
I tested maximize, minimize, change the size and the issue remains the same. It seems the Outline cpauters about 75% of the main window and clones the content

**Comment by Phillipus** [comment]
Changed the title of this issue to focus on the Outline rendering problem. The Backspace key problem above was a separate issue.

**Comment by xmstspider** [comment]
Ow, tried to move the Outline window beside the main window and I see the problem now - there are acutally TWO Outline windows, one covering the other one with at about 75% of the size

**Comment by Phillipus** [comment]
Wow. So does each one work OK?

**Comment by xmstspider** [comment]
I tried to create a picture depicting the issue:
![archiissue](https://user-images.githubusercontent.com/7497125/46406960-9a2ddf80-c70d-11e8-86b3-394cb796abd5.png)

If you expand the size, the content may be not just doubled, but quadrupled :-O

**Comment by xmstspider** [comment]
Wow, even better, check this out: New document, places one single component.
![screenshot 2018-10-03 at 13 13 29](https://user-images.githubusercontent.com/7497125/46407219-6bfccf80-c70e-11e8-9ba9-b531253e7d5c.png)

**Comment by xmstspider** [comment]
I am testing JDK 11 which I have on the MAC on Windows now...hmm no change on Windows, still working

**Comment by xmstspider** [comment]
OK, I checked the Mojave release notes and the only graphical related note is about deprecation of OpenGL and OpenCL... 

> As of macOS Mojave, OpenGL and OpenCL are deprecated. They are still supported by the operating system, but will no longer be maintained; developers are encouraged to use Apple's Metal library instead. macOS does not natively support Vulkan, the official successor to OpenGL. While the MoltenVK library provides an implementation of Vulkan that operates within Metal, its compatibility is limited.

**Comment by pcdavid** [comment]
I believe I've already seen this (or very similar issues) on earlier versions of Sirius under Linux. It seems related somehow to HiDPI and "large" canvases but given that GEF (where the problem's root probably is) is unmaintained I did not investigate further.

**Comment by Phillipus** [comment]
@pcdavid Thanks. Obeo tools (Sirius, Obeo Designer, etc) use an Outline View. Do they use the GEF/Draw2D components to draw the thumbnail. Have you tested these on a Mac with Mojave OS?

@xmstspider Is your Mac a Hi-res display?

**Comment by pcdavid** [comment]
Yes, Sirius is based on GMF Runtime, itself based on GEF Legacy (3.x), and to my knowledge we use the outline view "as is".

**Comment by xmstspider** [comment]
Yes is it, now it's connected to 25" QHD screen, the same as the Windows computer, which is also HiDPI.

**Comment by Phillipus** [comment]
@xmstspider @trainsatsea Let's see it it's related to Hi-res. If you right click the Archi app and select "Get Info" and in the Info box select "Open in Low Resolution" and re-launch Archi does that fix the problem?

**Comment by trainsatsea** [comment]
looks like the same issue as i now switched to low res and nothing is shown in the outline.

<img width="1620" alt="schermafbeelding 2018-10-03 om 16 40 30" src="https://user-images.githubusercontent.com/18326651/46418023-2dc1d900-c72b-11e8-94a6-6d0d67ad854a.png">

or  it shows the same result, being duplicate or quadruple 
<img width="1348" alt="schermafbeelding 2018-10-03 om 16 42 21" src="https://user-images.githubusercontent.com/18326651/46418160-7ed1cd00-c72b-11e8-9d94-bc30c58ec3e6.png">

so lowres is not fixing the issue. This setting is made as requested.
<img width="290" alt="schermafbeelding 2018-10-03 om 16 44 27" src="https://user-images.githubusercontent.com/18326651/46418220-a3c64000-c72b-11e8-82ed-a9ef9ad36816.png">

**Comment by Phillipus** [comment]
We need to see if this problem is on other Eclipse-based apps like Eclipse Sirius diagrams and the "Ecore Diagram Editor".

**Comment by sbegaudeau** [comment]
I can reproduce this issue using my own diagrams on Mojave, it is not related to Archi nor Sirius. It must come from GEF directly.

**Comment by Phillipus** [comment]
@sbegaudeau Thanks for the information. Is this in an Obeo tool?

The classes that are used for an outline are as follows. Searching through code in Github many different apps use the same technique:

        ScalableFreeformRootEditPart editPart; // Get EditPart
        
        Canvas canvas = new Canvas(parent, SWT.NONE); // Canvas
        LightweightSystem lws = new LightweightSystem(canvas); // Draw2d LWS
        
        ScrollableThumbnail thumbnail = new ScrollableThumbnail((Viewport)editPart.getFigure());
        thumbnail.setSource(editPart.getLayer(LayerConstants.PRINTABLE_LAYERS));
        thumbnail.setBorder(new MarginBorder(3));
        lws.setContents(thumbnail);

So I wonder if the problem is in:

`org.eclipse.draw2d.LightweightSystem`

or 

`org.eclipse.draw2d.parts.ScrollableThumbnail`

**Comment by pcdavid** [comment]
@Phillipus Answering for @sbegaudeau : yes it was using Sirius that he reproduced the issue.

**Comment by Phillipus** [comment]
@pcdavid Thanks.

I think there are many tools that use a thumbnail in an Outline view and will be hit by this issue. See for example code examples in GitHub:

https://github.com/search?p=2&q=org.eclipse.draw2d.parts.ScrollableThumbnail&type=Code.

It might be possible create a patch if the problem is in one of the Draw2D classes I mentioned. I can't run Mojave so not possible for me to look into.

Is this something that you think is worth doing?

**Comment by Phillipus** [comment]
> I just went out and bought a 2017 MacBook Pro 13" with Retina display so I could test this. It has Mojave 10.13.4 and Archi 4.3.1 and the thumbnail is rendering OK for me.

My bad. I hadn't installed Mojave. Now that I have I see the same problem in the thumbnail. Obviously, this is caused by Mojave as it is OK in High Sierra. I'll try to dig a little deeper into this...

**Comment by Phillipus** [comment]
Now we need to find out if it's caused by Mojave or Retina Display, I put my money on Mojave.

Perhaps somebody could test Archi on Mojave with a non-Retina display and report back.

**Comment by Phillipus** [comment]
I've narrowed the issue down to `org.eclipse.draw2d.parts.Thumbnail` and the `ThumbnailUpdater` inner class.

If I set MAX_NUMBER_OF_TILES to 1 instead of 16 it fixes the problem. 

Here's what I did:

- Get the Source code of `org.eclipse.draw2d.parts.Thumbnail` and  `org.eclipse.draw2d.parts.ScrollableThumbnail` and copy these classes to the `com.archimatetool.editor.diagram` package.
- Edit `com.archimatetool.editor.diagram.OverviewOutlinePage` import statements by removing `import org.eclipse.draw2d.parts.ScrollableThumbnail;`
- Edit the copied `Thumbnail` class to this:

`private static final int MAX_NUMBER_OF_TILES = 1;`

Now run it and the issue is fixed.

But I don't know why this should be so and whether the issue is related to Mac Mojave or hi-res Retina display.

@trainsatsea @xmstspider Do you have access to a non-Retina Mac with Mojave? Or does anybody who would like to help?

**Comment by xmstspider** [comment]
@Phillipus No I don't have unfortunately, but my Linux and Windows are running both FHD and 4K and I don't see this problem there.

Regarding the MAX_NUMBER_OF_TILES - does it affect anything else? Like fixing this problem but breaking something else?

**Comment by Phillipus** [comment]
@xmstspider I've set a condition on this to only apply this change on Mac 10.14 (Mojave) and greater versions, so it won't affect Linux, Windows, or earlier MacOS. I just need to check if it is caused by Mojave _and_ Retina display, or just Mojave.

So far I can't see any side issues with the patch. I've asked the Eclipse developers on their forum but don't expect a reply - https://www.eclipse.org/forums/index.php/t/1097158/

**Comment by Phillipus** [comment]
@xmstspider Would you like to test the patched version on Mojave?

Here's a build - https://www.archimatetool.com/downloads/temp/Archi-Mac-4.3.2-test.zip

**Comment by Phillipus** [comment]
Just a note to say that the Thumbnail Outline view in the Modelio tool exhibits the same behaviour. If only there was an Eclipse expert who could provide a proper fix... ;-)

**Comment by xmstspider** [comment]
Hmm can't now, the MBP is back now. Hopefully I can set up a virtual Mojave to see if there are same issue.
I hope someone can test it.

BTW could you compile the patched version for Linux/Windows so I can check if there are any side effects?

**Comment by Phillipus** [comment]
> BTW could you compile the patched version for Linux/Windows so I can check if there are any side effects?

No need. The change affects only Mac and Mojave.

**Comment by Phillipus** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=309912

**Comment by Phillipus** [comment]
It gets interesting and actually is to do with SWT and GC.drawGraphics().

In the Thumbnail$ThumbnailUpdater class an image tile is drawn:

```
// Copy the painted tile image into the thumbnail image.
thumbnailGC.drawImage(tileImage, 0, 0, sx2 - sx1, sy2 - sy1, sx1,
    sy1, sx2 - sx1, sy2 - sy1);
```

However, even though tileImage contains the correct image before the drawImage() call it contains the first tile image after it is called. It is as if something in SWT is caching the first image and replacing it..

I've managed to boil this down to a Snippet and raised a bug - https://bugs.eclipse.org/bugs/show_bug.cgi?id=543796

If, however, we make a copy of tileImage it works:

```
// Don't re-use the same tileImage
Image tmp = new Image(tileImage.getDevice(), tileImage.getImageData());
                
 // Copy the painted tile image into the thumbnail image.
thumbnailGC.drawImage(tmp, 0, 0, sx2 - sx1, sy2 - sy1, sx1,
       sy1, sx2 - sx1, sy2 - sy1);
                
tmp.dispose();
```

**Comment by Phillipus** [comment]
Patched in Archi 4.3.2. Please re-open if the issue re-occurs.

**Comment by Phillipus** [comment]
This bug is back again in Eclipse 4.13 but this time I don't have a fix and I'm not prepared to spend another 2 weeks investigating it.

It's up to someone else to take a look at it, because trying to fix every bug on Mac is now turning into a full time job.

**Comment by jbsarrodie** [comment]
Hi,

My personnal advice on this would be to concentrate on Windows version of Archi (which is more than 80% of users) and consider Linux and Mac as best effort only.

If we agree on this, this should be made clear on the download page with a link to a 'known bugs' wiki page here.

**Comment by Phillipus** [comment]
@jbsarrodie I agree.

(But I need to express how pissed off I get with Eclipse and Mac ;-) )

For reference I think it might be cause by this - https://bugs.eclipse.org/bugs/show_bug.cgi?id=489451

**Comment by brynwales** [comment]
Sorry, I don’t agree, the cross platform is one of Archi’s strengths.

**Comment by Phillipus** [comment]
> Sorry, I don’t agree, the cross platform is one of Archi’s strengths.

Yes, but...

...this particular bug has cost me about 3 or 4 weeks of my life and the purchase of a very expensive MacBook (which I can barely use because of its terrible keyboard) to test it. Archi is apparently "open source" but I personally see no benefit in that whatsoever. Without help to solve these issues then I'm afraid Mac support will go by the wayside. And I might be able to get my life back. :-)

**Comment by xmstspider** [comment]
> Sorry, I don’t agree, the cross platform is one of Archi’s strengths.
Without help to solve these issues then I'm afraid Mac support will go by the wayside. And I might be able to get my life back. :-)

Phil, I've got access to some Macs 2010-2018 so I would be able to do some limited testing and continue supporting through PayPal. Other that that, I don't have the right skills for developing this wonderful piece of software.

On the other side, there are no serious bugs on Linux, aren't they? So it could be still considered  on the same support level as the Windows one?

**Comment by Phillipus** [comment]
@xmstspider 

H Zdenek, thanks for your support, I really appreciate it. :-) Don't worry, I have a workaround for this particular bug (only took a day this time ;-) ) see https://github.com/archimatetool/archi/commit/c247ef54211519bc8434444a4de010849660f581

The problem with Mac issues like this is that there is someone out there who knows what the real issue is (Eclipse experts) but they don't want to help or advise, so for them it's better that I struggle for weeks in trial and error. ;-)

Anyway, tomorrow there will be a beta of Archi 4.6. :-)
